apiVersion: apps/v1
kind: Deployment
metadata:
  name: calculator-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: calculator-app
  template:
    metadata:
      labels:
        app: calculator-app
    spec:
      containers:
      - name: calculator-app
        image: ganesh6498/java-harness:latest
        ports:
        - containerPort: 8085
        # env:
        # - name: SPRING_PROFILES_ACTIVE
        #   value: "prod"

---
apiVersion: v1
kind: Service
metadata:
  name: calculator-app-service
spec:
  selector:
    app: calculator-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8085
  type: LoadBalancer  # If using a cloud provider, otherwise use ClusterIP
